name: deploy package
on:
  push:
    branches:
      - Add-python-example
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: build and publish python project
        run: |
          jfrog rt pip-config --repo-resolve default-pypi --server-id-resolve artifactory-server1   
          jfrog rt bce my-new-pip-build 1
          jfrog rt bp my-new-pip-build 1
          jfrog rt pipi -r requirements.txt --build-name=my-new-pip-build --build-number=1 --module=test
          python setup.py sdist bdist_wheel
          jfrog rt u dist/ default-pypi/simple/ --build-name=my-new-pip-build --build-number=1 --module=test
          pip show jfrog-python-example
